module.exports = {
  BROWSER_ERROR: "BROWSER_ERROR",
  SELECT_COMPOSITION: "SELECT_COMPOSITION",
  RECEIVE_COMPOSITIONS: "RECEIVE_COMPOSITIONS",

  UPDATE_SEARCH_STRING: "UPDATE_SEARCH_STRING",
  CLEAR_SEARCH_STRING: "CLEAR_SEARCH_STRING"
};
