module.exports = {
  NEW_COMPOSITION: "NEW_COMPOSITION",
  LOAD_COMPOSITION: "LOAD_COMPOSITION",
  CREATE_COMPOSITION: "CREATE_COMPOSITION",
  UPDATE_COMPOSITION: "UPDATE_COMPOSITION",
  DELETE_COMPOSITION: "DELETE_COMPOSITION"
};
