module.exports = {
  CELL_WIDTH: 24,
  CELL_HEIGHT: 12,
  NOTE_TAIL_WIDTH: 6,
  GRID_COLOR: "#777",
  NOTE_COLOR: "#a11",
  NOTE_TAIL_COLOR: "#811",

  LOAD_PHRASE: "LOAD_PHRASE",

  INSERT_NOTE: "INSERT_NOTE",
  REMOVE_NOTE: "REMOVE_NOTE",
  MOVE_NOTE_TO: "MOVE_NOTE_TO",
  REISZE_NOTE_TO: "REISZE_NOTE_TO",

  SELECT_NOTE_FOR_MOVE: "SELECT_NOTE_FOR_MOVE",
  SELECT_NOTE_FOR_RESIZE: "SELECT_NOTE_FOR_RESIZE",
  DRAG_NOTE_OVER_CELL: "DRAG_NOTE_OVER_CELL",
  DRAG_COMPLETED: "DRAG_COMPLETED"
};
