module.exports = {
  INSERT_NOTE: "INSERT_NOTE",
  REMOVE_NOTE: "REMOVE_NOTE",
  MOVE_NOTE_TO: "MOVE_NOTE_TO",
  REISZE_NOTE_TO: "REISZE_NOTE_TO",

  SELECT_NOTE_FOR_MOVE: "SELECT_NOTE_FOR_MOVE",
  SELECT_NOTE_FOR_RESIZE: "SELECT_NOTE_FOR_RESIZE",
  DRAG_NOTE_OVER_CELL: "DRAG_NOTE_OVER_CELL",
  DRAG_COMPLETED: "DRAG_COMPLETED"
};
