module.exports = {
  CELL_WIDTH: 24,
  CELL_HEIGHT: 12,
  NOTE_TAIL_WIDTH: 10,
  GRID_COLOR: "#666",
  GRID_BAR_COLOR: "#aaa",
  NOTE_COLOR: "#a11",
  SELECT_COLOR: "#d8863a",
  NOTE_TAIL_COLOR: "#411",
  KEY_PATTERN: [0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1],

  INSERT_NOTE: "INSERT_NOTE",
  REMOVE_NOTE: "REMOVE_NOTE",

  TOGGLE_NOTE_SELECTION: "TOGGLE_NOTE_SELECTION",
  SELECT_NOTE: "SELECT_NOTE",
  DESELECT_NOTE: "DESELECT_NOTE",
  CLEAR_NOTE_SELECTION: "CLEAR_NOTE_SELECTION",

  START_MOVE_DRAG: "START_MOVE_DRAG",
  CONTINUE_MOVE_DRAG: "CONTINUE_MOVE_DRAG",
  COMPLETE_MOVE_DRAG: "COMPLETE_MOVE_DRAG",

  START_RESIZE_DRAG: "START_RESIZE_DRAG",
  CONTINUE_RESIZE_DRAG: "CONTINUE_RESIZE_DRAG",
  COMPLETE_RESIZE_DRAG: "COMPLETE_RESIZE_DRAG",

  SELECT_KEY: "SELECT_KEY",

  SET_TEMPO: "SET_TEMPO",
  UPDATE_COMPOSITION_SETTINGS: "UPDATE_COMPOSITION_SETTINGS",

  UPDATE_SYNTH: "UPDATE_SYNTH",

  SELECT_TRACK: "SELECT_TRACK",
  ADD_TRACK: "ADD_TRACK",
  REMOVE_TRACK: "REMOVE_TRACK",

  RESIZE_PATTERN: "RESIZE_PATTERN"
};
